#!/usr/bin/env bash
# Copyright (C) 2020-2021 Oktapra Amtono
# Docker Kernel Build Script

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'"%h : %s"' -5)

CLANG_DIR="clang"
CCV="$("$CLANG_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
LDV="$("$CLANG_DIR"/bin/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
LINUX_VERSION=$(cat < out/.config | grep Linux/arm64 | cut -d " " -f3)

export BRANCH

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendInfo  "<b>======================================</b>" \
          "<b> Success Building : </b><code>Mystic Kernel</code>" \
          "<b> Linux Version : <code>$LINUX_VERSION</code> </b>" \
          "<b> Toolchain : <code>$CCV</code> </b>" \
          "<b> Linker : <code>$LDV</code> </b>" \
          "<b> Changelog from Last Commit</b> : " \
          "<b> <code>- $COMMIT</code> </b>" \
          "<b>======================================</b>"
