#!/usr/bin/env bash
# Copyright (C) 2020-2021 Oktapra Amtono
# Docker Kernel Build Script

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'"%h : %s"' -5)

CLANG_DIR="clang"
KBUILD_COMPILER_STRING="$(${CLANG_DIR}/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"

export BRANCH
export KBUILD_COMPILER_STRING

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendInfo	"<b>======================================</b>" \
        	"<b> Successfully Build : </b><code>Mystic Kernel</code>" \
        	"<b> Using Toolchain : </b><code>$KBUILD_COMPILER_STRING</code>" \
        	"<b> Changelog from Last Commit</b> : " \
        	"<b> <code>$COMMIT</code> </b>" \
        	"<b>======================================</b>"
