#!/usr/bin/env bash
# Copyright (C) 2020-2021 Oktapra Amtono
# Docker Kernel Build Script

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'%s' -1)

CLANG_DIR="clang"
CCV="$("$CLANG_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
LDV="$("$CLANG_DIR"/bin/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
LINUX_VERSION=$(cat < out/.config | grep Linux/arm64 | cut -d " " -f3)

export BRANCH

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendInfo  "<b>======================================</b>" \
          "<b>Success Building :</b> <code>Mystic Kernel</code>" \
          "<b>Linux Version :</b> <code>$LINUX_VERSION</code>" \
          "<b>Toolchain :</b> <code>$CCV</code>" \
          "<b>Linker :</b> <code>$LDV</code>" \
          "<b>Last Commit :</b> <code>$COMMIT</code>" \
          "<b>======================================</b>" \
          " " \
          "<b>Provide your feedback in the @MysticKernelDiscussion group for this Beta Build 😉</b>"
