#!/usr/bin/env bash
# Copyright (C) 2020-2021 Oktapra Amtono
# Docker Kernel Build Script

# Setup Environtment
KERNEL_DIR=$PWD
export TZ="Asia/Jakarta"
ZIP_DATE=$(TZ=Asia/Jakarta date +'%d%m%Y')
SOURCE="$(git rev-parse --abbrev-ref HEAD)"

# Kernel & Clang Setup
CLANG_DIR="$KERNEL_DIR/clang"
export PATH="$KERNEL_DIR/clang/bin:$PATH"
CCV="$("$CLANG_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
LDV="$("$CLANG_DIR"/bin/ld.lld --version | head -n 1)"

export ZIP_DATE
export SOURCE
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_COMPILER_STRING="$CCV + $LDV"
export KBUILD_BUILD_USER="okta_10"
export KBUILD_BUILD_HOST="dockerci"

if [[ "$*" =~ "stable" ]]; then
  RELEASE="Stable"
elif [[ "$*" =~ "beta" ]]; then
  RELEASE="Beta"
fi

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendKernel() {
  "${TELEGRAM}" -f "$(echo "$AK3_DIR"/*.zip)" \
  -c "${CHANNEL_ID}" -H \
      "# <code>$DEVICE-$CAM_BLOB</code> # <code>MD5-Checksum: $(md5sum "$AK3_DIR"/*.zip | cut -d' ' -f1)</code>"
}

# Setup Kernel IMG
# for whyred and tulip, build with dtbs for overclock and non-overclock
if [[ "$*" =~ "sdm636" ]]; then
  KERNEL_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz
# for lavender and a26x (jasmine/wayne)
elif [[ "$*" =~ "sdm660" ]]; then
  KERNEL_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb
fi

# Setup Defconfig
# if whyred
if [[ "$*" =~ "whyredoldcam" ]]; then
  export DEVICE="Whyred"
  AK3_DIR=$KERNEL_DIR/ak3-whyred/
  export KERNEL_DEFCONFIG=mystic-whyred-oldcam_defconfig
  export CAM_BLOB="OldCam"
elif [[ "$*" =~ "whyrednewcam" ]]; then
  export DEVICE="Whyred"
  AK3_DIR=$KERNEL_DIR/ak3-whyred/
  export KERNEL_DEFCONFIG=mystic-whyred-newcam_defconfig
  export CAM_BLOB="NewCam"
# if tulip
elif [[ "$*" =~ "tulipoldcam" ]]; then
  export DEVICE="Tulip"
  AK3_DIR=$KERNEL_DIR/ak3-tulip/
  export KERNEL_DEFCONFIG=mystic-tulip-oldcam_defconfig
  export CAM_BLOB="OldCam"
elif [[ "$*" =~ "tulipnewcam" ]]; then
  export DEVICE="Tulip"
  AK3_DIR=$KERNEL_DIR/ak3-tulip/
  export KERNEL_DEFCONFIG=mystic-tulip-newcam_defconfig
  export CAM_BLOB="NewCam"
# if lavender
elif [[ "$*" =~ "lavenderoldcam" ]]; then
  export DEVICE="Lavender"
  AK3_DIR=$KERNEL_DIR/ak3-lavender/
  export KERNEL_DEFCONFIG=mystic-lavender-oldcam_defconfig
  export CAM_BLOB="OldCam"
elif [[ "$*" =~ "lavendernewcam" ]]; then
  export DEVICE="Lavender"
  AK3_DIR=$KERNEL_DIR/ak3-lavender/
  export KERNEL_DEFCONFIG=mystic-lavender-newcam_defconfig
  export CAM_BLOB="NewCam"
# if a26x
elif [[ "$*" =~ "a26xoldcam" ]]; then
  export DEVICE="A26X" #Jasmine/Wayne
  AK3_DIR=$KERNEL_DIR/ak3-a26x/
  export KERNEL_DEFCONFIG=mystic-a26x-oldcam_defconfig
  export CAM_BLOB="OldCam"
elif [[ "$*" =~ "a26xnewcam" ]]; then
  export DEVICE="A26X" #Jasmine/Wayne
  AK3_DIR=$KERNEL_DIR/ak3-a26x/
  export KERNEL_DEFCONFIG=mystic-a26x-newcam_defconfig
  export CAM_BLOB="NewCam"
elif [[ "$*" =~ "a26xtencam" ]]; then
  export DEVICE="A26X" #Jasmine/Wayne
  AK3_DIR=$KERNEL_DIR/ak3-a26x/
  export KERNEL_DEFCONFIG=mystic-a26x-tencam_defconfig
  export CAM_BLOB="TenCam"
# if tulip MSM Thermal
elif [[ "$*" =~ "msmtulipold" ]]; then
  export DEVICE="Tulip"
  AK3_DIR=$KERNEL_DIR/ak3-tulip/
  export KERNEL_DEFCONFIG=mystic-tulip-oldcam_defconfig
  export CAM_BLOB="OldCam_MSM-Thermal"
elif [[ "$*" =~ "msmtulipnew" ]]; then
  export DEVICE="Tulip"
  AK3_DIR=$KERNEL_DIR/ak3-tulip/
  export KERNEL_DEFCONFIG=mystic-tulip-newcam_defconfig
  export CAM_BLOB="NewCam_MSM-Thermal"
fi

# Start Compile
make O=out $KERNEL_DEFCONFIG
make -j"$(nproc --all)" O=out \
        CC=clang \
        AR=llvm-ar \
        NM=llvm-nm \
        OBJCOPY=llvm-objcopy \
        OBJDUMP=llvm-objdump \
        STRIP=llvm-strip \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi-

# If build error
if ! [ -a "$KERNEL_IMG" ]; then
  sendInfo "<b>Failed building kernel for <code>$DEVICE-$RELEASE-$CAM_BLOB</code> Please fix it...!</b>"
  exit 1
fi

# Make zip
# for whyred and tulip, build with dtbs for overclock and non-overclock
if [[ "$*" =~ "sdm636" ]]; then
  cp -r "$KERNEL_IMG" "$AK3_DIR"/kernel/
# for lavender and a26x (jasmine/wayne)
elif [[ "$*" =~ "sdm660" ]]; then
  cp -r "$KERNEL_IMG" "$AK3_DIR"/
fi
cd "$AK3_DIR" || exit
if [[ "$*" =~ "stable" ]]; then
  zip -r9 Mystic-EAS_"$DEVICE"_"$CAM_BLOB".zip ./*
elif [[ "$*" =~ "beta" ]]; then
  zip -r9 Mystic-EAS_"$DEVICE"_"$RELEASE"_"$CAM_BLOB"_"$ZIP_DATE".zip ./*
fi
cd "$KERNEL_DIR" || exit

sendKernel

rm -rf out/arch/arm64/boot/
rm -rf out/.version
rm -rf "$AK3_DIR"/*.zip
