#!/usr/bin/env bash
# Copyright (C) 2020-2021 Oktapra Amtono
# Docker Kernel Build Script

SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'%s' -1)

LINUX_VERSION=$(cat < out/.config | grep Linux/arm64 | cut -d " " -f3)

export SOURCE

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H -D \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendInfo  "<b>======================================</b>" \
          "<b>Success Building :</b> <code>Mystic Kernel</code>" \
          "<b>Linux Version :</b> <code>$LINUX_VERSION</code>" \
          "<b>Build Date :</b> <code>$(date +"%A, %d %b %Y, %H:%M:%S")</code>" \
          "<b>Last Changelog :</b> <code>$COMMIT</code>" \
          "<b>======================================</b>" \
          " " \
          "<b>Provide your feedback in the @MysticKernelDiscussion group for this Beta Build 😉</b>"
